services:
  api:
    build: ..
    image: ielts-playground-api-v2:0.19.4
    container_name: ielts-playground-api-v2
    ports:
      - 8090:8090
    environment:
      - EXPORTER_SERVICE=http://exporter:8080
      - SWAGGER_SERVICE=http://swagger:8090
    volumes:
      - pb_data:/pb
    networks:
      - ielts-playground-v2
  exporter:
    build:
      context: ..
      dockerfile: services/exporter/Dockerfile
    image: ielts-playground-api-v2-exporter:1
    container_name: ielts-playground-api-v2-exporter
    depends_on:
      - api
    volumes:
      - pb_data:/pb/pb_data
    environment:
      - EXPORTER_PORT=8080
    expose:
      - 8080
    networks:
      - ielts-playground-v2
  swagger:
    build:
      context: ..
      dockerfile: services/swagger/Dockerfile
    image: ielts-playground-api-v2-swagger:1
    container_name: ielts-playground-api-v2-swagger
    depends_on:
      - api
    environment:
      - PB_SERVICE=http://api:8090
      - SWAGGER_PORT=8090
    expose:
      - 8090
    networks:
      - ielts-playground-v2

volumes:
  pb_data:
    name: ielts-playground-v2
    driver: local

networks:
  ielts-playground-v2:
    name: ielts-playground-v2
    driver: bridge

