#!/bin/sh

[ -z "$1" ] && echo "Error: hook name is missing." && exit 1

hook="src/$1.pb.ts"

if [ -f "$hook" ]; then
    echo "Error: hook '$1' existed."
    exit 1
else
    echo -n "/// <reference path=\"../types/pocketbase.d.ts\" />\n\n" > $hook
    echo "Success: hook '$1' added."
fi