#!/bin/sh

if [ -z "$1" ]; then
    echo "Error: action missing."
    exit 1
elif [ "$1" = "up" ]; then
    [ "$2" = "reset" ] && docker volume rm "ielts-playground-v2" > /dev/null || test true
    [ "$2" = "reset" ] && docker volume rm "ielts-playground-v1" > /dev/null || test true
    docker compose --project-directory .docker up -d --build
elif [ "$1" = "down" ]; then
    docker compose --project-directory .docker down
    [ "$2" = "reset" ] && docker volume rm "ielts-playground-v2" > /dev/null || test true
    [ "$2" = "reset" ] && docker volume rm "ielts-playground-v1" > /dev/null || test true
else
    echo "Error: action invalid."
    exit 1
fi