#!/bin/bash

[ -z "$1" ] && echo "Error: action missing." && exit 1

DOCKER_CLI_PLUGINS=$HOME/.docker/cli-plugins
DOCKER_COMPOSE_VERSION="2.23.3"

install_compose_plugin() {
    mkdir -p ${DOCKER_CLI_PLUGINS} && \
        curl -SL https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-linux-x86_64 -o ${DOCKER_CLI_PLUGINS}/docker-compose && \
        chmod +x ${DOCKER_CLI_PLUGINS}/docker-compose
}

docker compose version 2> /dev/null || (install_compose_plugin && docker compose version)

remove_volumes() {
    declare -a volumes=("ielts-playground-v1" "ielts-playground-v2")
    for volume in ${volumes[@]}; do
        docker volume rm $volume &> /dev/null && \
            echo -e " ✔ Volume \"$volume\"\tRemoved" || test true
    done
}

restart_nginx() {
    docker restart ielts-playground-api-nginx &> /dev/null
}

if [ "$1" = "up" ]; then
    [ "$2" = "reset" ] && remove_volumes
    docker compose --project-directory .docker up -d --build
    restart_nginx
elif [ "$1" = "down" ]; then
    docker compose --project-directory .docker down
    [ "$2" = "reset" ] && remove_volumes
else
    echo "Error: action invalid."
    exit 1
fi

test true